### ISSUE TITLE
Занести все css файлы в папку css

### ISSUE THREAD

**Issue by ArseniyDuck** [brotegor/first-project#10]
... и не забыть обновить пути в `index.html`

**Comment by brotegor** [comment]
Я когда создавал ветку перешел в main, а там старые файлы, которые уже удалены, поэтому в VSCode файлы не видны, а в самой папке с проектом два старых файла main.html и main.css. Насколько я понял.

**Comment by brotegor** [comment]
Как открыть html и css, которые в гитхабе сохранены?

**Comment by ArseniyDuck** [comment]
чтобы загрузить изменения с гита, надо сделать `git pull`

**Comment by brotegor** [comment]
git branch выдает
  issue/10
  issue/4
* main
Можно работать?

**Comment by brotegor** [comment]
А так же два вопроса:
Можно ли файл в project переименовать и как писать кодом тут

**Comment by ArseniyDuck** [comment]
> git branch выдает issue/10 issue/4
> 
> * main
>   Можно работать?

ты сейчас на main, получается?

**Comment by brotegor** [comment]
Да

**Comment by brotegor** [comment]
Ветку создал

**Comment by ArseniyDuck** [comment]
ты ее из main создавал? она обязательно должна от main отталкиваться

**Comment by brotegor** [comment]
все как ты в readme писал сделал

**Comment by ArseniyDuck** [comment]
странно, что после `git checkout -b issue/10` ты остался в main. если ты сейчас в main, сделай `git checkout issue/10`, чтобы переключиться на существующую ветку, и начинай работать

**Comment by brotegor** [comment]
fatal: a branch named 'issue/10' already exists

**Comment by brotegor** [comment]
я ее создал перед тем как запулил все с гитхаба, может в этом проблема?

**Comment by ArseniyDuck** [comment]
> А так же два вопроса: Можно ли файл в project переименовать и как писать кодом тут

ты хочешь именно папку project переименовать? просто файлы ты уже переименовывал же

**Comment by brotegor** [comment]
именно саму папку

**Comment by ArseniyDuck** [comment]
> я ее создал перед тем как запулил все с гитхаба, может в этом проблема?

git checkout issue/10

**Comment by ArseniyDuck** [comment]
без -b

**Comment by ArseniyDuck** [comment]
> именно саму папку

переименовывай, это ни на что не влияет, по идее

**Comment by brotegor** [comment]
я запушил, но в pr пусто
