### ISSUE TITLE
Шрифты

### ISSUE THREAD

**Issue by brotegor** [brotegor/first-project#16]

**Comment by ArseniyDuck** [comment]
Асан, иди на [этот сайт](https://fonts.google.com/) и выбери шрифт.  
Как выберешь шрифт, кликай на него и выбери шрифты 400 и 700. Делается это так: ![image](https://user-images.githubusercontent.com/67900946/213928311-d48ac544-6771-4246-86c3-c9074cdbf7ad.png)
Потом справа вылезет вот такое окно 
![image](https://user-images.githubusercontent.com/67900946/213928363-36bdbdc1-f5eb-4be4-9d32-a02b13c70d5e.png)
Копируешь этот тег и вставляешь в index.html рядом с другими link.

**Comment by ArseniyDuck** [comment]
Делай все как в readme про порядок работы
