### ISSUE TITLE
Начало работы

### ISSUE THREAD

**Issue by ArseniyDuck** [brotegor/first-project#19]
Предлагаю определиться с темой. Просто сейчас я совсем не вижу идеи на сайте, и из-за этого сквозь пальцы смотрю на кое-какие моменты: все равно придется это переделывать.  
Надо сделать макет (не обязательно детальный) в [фигме](https://www.figma.com/), где сами собой решатся задачи #15 и #16.  
Сначала пишите сюда свои идеи, и я подумаю над реализацией. Я о том, что вы, скорее всего, не будете знать, что возможно сделать, а что нет. С реализацией помогу.

**Comment by asanmmv** [comment]
https://www.figma.com/file/UAlG0HzxjQx1Vr8Pyv1oer/Untitled?t=zYox8YECzncFtwyZ-0

**Comment by ArseniyDuck** [comment]
Могу сразу сказать, что нам понадобится [React](https://ru.reactjs.org/). Пока над этим не слишком заморачивайтесь, но если мы хотим иметь любые не хардкоженые в html данные, то нам нужна база данных. Это подразумевает backend и frontend. Пока делайте дизайн и верстайте страницы, но рано или поздно все равно нужен будет React.
