### ISSUE TITLE
Перейти на React

### ISSUE THREAD

**Issue by ArseniyDuck** [brotegor/first-project#22]
Как я писал [здесь](https://github.com/brotegor/first-project/issues/19#issuecomment-1401929956), рано или поздно надо было бы перейти на React. Пока его возможности затрагивать целиком не будем. Просто верстаем как обычно, но на React.

**Comment by ArseniyDuck** [comment]
Сегодня вечером решу эту issue и напишу Readme по тому, как с этим работать.

**Comment by ArseniyDuck** [comment]
Пустое приложение уже сделал. Осталось только существующий код на React переписать

**Comment by ArseniyDuck** [comment]
Забыл переключиться на ветку для этой issue, поэтому изменения залью сразу в `main`, не создавая pr.

**Comment by ArseniyDuck** [comment]
Readme писать некогда, сделаю позже. Пока можете рыться в коде и смотреть, как оно работает.

**Comment by brotegor** [comment]
Я могу без реакта запулить main?

**Comment by ArseniyDuck** [comment]
да, но надо скачать nodejs
