### ISSUE TITLE
Страница профиля

### ISSUE THREAD

**Issue by brotegor** [brotegor/first-project#25]
Сверстать по макету страницу профиля. url пусть будет `/profile`.

**Comment by VigesSvet** [comment]
Я всё забыл. Как создать url и как создавать определенные фигуры?

**Comment by ArseniyDuck** [comment]
Читал Readme?

**Comment by VigesSvet** [comment]
Да

**Comment by ArseniyDuck** [comment]
ветку создал?

**Comment by ArseniyDuck** [comment]
https://github.com/brotegor/Arystan/blob/main/docs/react.md#%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5-%D0%BD%D0%BE%D0%B2%D0%BE%D0%B9-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D1%8B
