### ISSUE TITLE
Добавить лого в header

### ISSUE THREAD

**Issue by ArseniyDuck** [brotegor/first-project#4]
Лого должно быть выравнено по левому краю и не должно сдвигать заголовок с центра экрана.

**Comment by brotegor** [comment]
должно

**Comment by ArseniyDuck** [comment]
что должно

**Comment by brotegor** [comment]
лого должно

**Comment by brotegor** [comment]
быть выравнено по левому краю и не должно сдвигать заголовок с центра экрана.

**Comment by brotegor** [comment]
че теперь делать

**Comment by ArseniyDuck** [comment]
аххахаха, я просто описал issue. логично, что должно

**Comment by ArseniyDuck** [comment]
> че теперь делать

теперь иди в телегу и создавай ветку с именем issue/4, т.к. id этой issue это 4

**Comment by ArseniyDuck** [comment]
ветки лучше так называть

**Comment by brotegor** [comment]
Появилась проблема в виде окончания моих знаний, близких нулю, не соизволите ли указать мне на источники информации, откуда я с удовольствием буду черпать знания

**Comment by brotegor** [comment]
или просто дай мне завтрашний день на обучение, чтобы я тебя обо всем не спрашивал

**Comment by ArseniyDuck** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS
https://www.w3schools.com/css/

**Comment by ArseniyDuck** [comment]
> или просто дай мне завтрашний день на обучение, чтобы я тебя обо всем не спрашивал

спрашивай сколько влезет

**Comment by brotegor** [comment]
че по позиционированию
мне нужно чтобы внутри шапки лого было слева, а надпись по центру

**Comment by ArseniyDuck** [comment]
> Появилась проблема в виде окончания моих знаний, близких нулю, не соизволите ли указать мне на источники информации, откуда я с удовольствием буду черпать знания

А так можешь просто гуглить то, что хочешь. Просто формулируй проблему как можно короче и тебе, скорее всего, вылезет ссылка на нужный раздел в тех сайтах, которые я скинул. И гуглить эффективнее на английском

**Comment by ArseniyDuck** [comment]
> че по позиционированию мне нужно чтобы внутри шапки лого было слева, а надпись по центру

можешь для `header` задать `position: relative;`, а для элемента с лого `position: absolute;`. потом лого прижимаешь к левому краю с помощью `left: 0;`

**Comment by brotegor** [comment]
с этим я справился

**Comment by brotegor** [comment]
появилась проблема с центровкой по oy

**Comment by ArseniyDuck** [comment]
в лого
```
top: 50%;
transform: translate(0, -50%);
```

**Comment by brotegor** [comment]
после добавления картинки в папку она не отображается

**Comment by brotegor** [comment]
починил

**Comment by ArseniyDuck** [comment]
если картинка лежит в корне, то путь до нее указывается просто как `image-name.jpg`

**Comment by brotegor** [comment]
чекни другие issue
