### ISSUE TITLE
Сброс дефолтных стилей

### ISSUE THREAD

**Issue by ArseniyDuck** [brotegor/first-project#5]
Надо создать файл `reset.css` для обнуления дефолтных стилей в браузерах. Это делается для того, чтобы верстка одинакого выглядела и в chrome, и в safari, и в любых других браузерах. Как основу можно взять [это](https://meyerweb.com/eric/tools/css/reset/).

**Comment by brotegor** [comment]
ее же нужно подключать к html файлу?

**Comment by brotegor** [comment]
reset не робит, хотя подключил и вроде все должно работать

**Comment by ArseniyDuck** [comment]
Когда зальешь все в pr, посмотрю, что не так. Так быстрее будет

**Comment by brotegor** [comment]
push origin надо?

**Comment by brotegor** [comment]
git add .
git commit -m 'description of the commit'
git push -u origin <branch-name>\
