### ISSUE TITLE
Разобраться с неймингом файлов

### ISSUE THREAD

**Issue by ArseniyDuck** [brotegor/first-project#6]
- [ ] `main.html` --> `index.html`
- [ ] `main.css`--> `style.css`
- [ ] создать файл с css переменными `variables.css`, куда можно занести, например, цвета
- [ ] создать папку `images`, куда складывать все скаченные изображения

**Comment by brotegor** [comment]
выполнено

**Comment by brotegor** [comment]
ты изменения видишь или их заливать надо?

**Comment by ArseniyDuck** [comment]
Надо коммитить и заливать. Тогда выполни сразу 3 задачи и залей их в один pull request. В нем обязательно укажи ссылки на эти задачи где-нибудь в описании.

**Comment by ArseniyDuck** [comment]
Вообще задачи подразумевают один pr на каждую, но раз ты решил делать все сразу, пусть для начала так и будет. В следующий раз, когда выполняешь одну задачу, в другие не лезь, пока не выполнишь ту, над которой работаешь

**Comment by brotegor** [comment]
понятно, со сбросом стилей проблемы
